name: my_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'
  flutter: '>=3.38.0'

dependencies:
  flutter:
    sdk: flutter
  # --- Routing ---
  go_router: ^17.0.1

  # --- State Management ---
  signals_flutter: ^6.3.0
  signals_hooks: ^0.4.0
  flutter_hooks: ^0.21.3+1

  # --- Dependency Injection ---
  get_it: ^9.2.0
  injectable: ^2.7.1+4

  # --- Network & API ---
  dio: ^5.9.0
  dio_smart_retry: ^7.0.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.9.2

  # --- Data & Persistence ---
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^10.0.0
  # isar_community: ^3.3.0
  # isar_community_flutter_libs: ^3.3.0
  path_provider: ^2.1.3

  # --- UI & Assets ---
  # chinese_font_library: ^1.2.0
  cached_network_image: ^3.4.1
  # flutter_carousel_widget: ^3.1.0
  line_icons: ^2.0.0
  flutter_gen: ^5.12.0
  lottie: ^3.3.2
  flutter_animate: ^4.5.2
  flutter_svg: ^2.2.3
  # cupertino_icons: ^1.0.8

  # --- Utils & Others ---
  logger: ^2.6.2
  device_info_plus: ^12.3.0
  flutter_dotenv: ^6.0.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

  # --- Code Generation ---
  build_runner: ^2.4.14
  # isar_community_generator: ^3.3.0
  json_serializable: ^6.9.3
  injectable_generator: ^2.12.0
  flutter_gen_runner: ^5.12.0
  retrofit_generator: ^10.2.1

# --- Flutter Launcher Icons Plugin ---
flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/icon/icon.png'

# --- Flutter Specific Settings ---
flutter:
  uses-material-design: true

  # --- Assets Configuration (Uncomment to use) ---
  assets:
    - .env
    - assets/json/lottie-404.json
    - assets/json/lottie-cta.json

  # --- Fonts Configuration (Uncomment to use) ---
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
